language: python
python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libudunits2-dev

env:
  global:
    - MPLBACKEND=agg

matrix:
  include:
    - name: "build artefacts"
      env: STAGE="build"
    - name: "rc artefacts"
      env: STAGE="rc"
    # 'production' stage is tested by default

install:
  - ./scripts/install_dependencies.sh
  - pip install coverage
  - pip install codecov

script:
  - coverage run setup.py test

after_success:
  - codecov
