language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
    - libudunits2-dev

env:
  global:
    - MPLBACKEND=agg

matrix:
  include:
    - name: "build artefacts"
      env: STAGE="build"
    - name: "systest artefacts"
      env: STAGE="systest"
    - name: "prod artefacts"
      env: STAGE="prod"

install:
  - ./scripts/install_dependencies.sh
  - pip install coverage
  - pip install codecov

script:
  - coverage run setup.py test

after_success:
  - codecov
