name: python-aodndata

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MPLBACKEND: agg

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]
        stage: [ 'build', 'rc', 'production']
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: additional required packages
      run: |
        sudo apt-get update &&
        sudo apt-get install -y --no-install-recommends \
        libudunits2-dev
    - name: cartopy - install additional required packages
      run: |
        sudo apt-get install -y --no-install-recommends \
        libproj-dev \
        libgeos-dev \
        libffi-dev \
        cmake \
        libgtest-dev \
        build-essential \
        curl \
        libcurl4-openssl-dev
    - name: cartopy - build Gtest needed for proj build
      run: |
        cd /usr/src/googletest && \
        sudo cmake . && \
        sudo cmake --build . --target install
    - name: cartopy - build proj 9.0.0
      run: |
        curl https://download.osgeo.org/proj/proj-9.0.0.tar.gz | tar -xz -C /tmp \
        && cd /tmp/proj-9.0.0/ \
        && mkdir build \
        && cd build \
        && cmake .. \
        && cmake --build && echo "THIS IS A TEST";
        sudo cmake --build . --target install
    - name: cartopy - libproj
      run: |
        sudo ldconfig
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-runner
        pip install numpy
        pip install pyshp
        #pip install shapely --no-binary shapely
        pip install scipy
        pip install -r stage_requirements.txt
        pip install pytest-cov
      env:
        STAGE: ${{ matrix.stage }}
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
