name: python-aodndata

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MPLBACKEND: agg

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.8' ]
        stage: [ 'build', 'rc', 'production']
    steps:
    - uses: actions/checkout@v2
    - name: Install libudunits2-dev
      run: |
        sudo apt install libudunits2-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install -r stage_requirements.txt
        pip install pytest-cov
      env:
        STAGE: ${{ matrix.stage }}
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
