name: python-aodndata

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MPLBACKEND: agg

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]
        stage: [ 'build', 'rc', 'production']
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: update apt-cache
      run: |
        sudo apt-get update &&
        sudo apt-get install -y software-properties-common --no-install-recommends &&
        sudo add-apt-repository -y -u ppa:ubuntugis/ubuntugis-unstable
    - name: install additional required packages
      run: |
        sudo apt-get install -y --no-install-recommends \
        libudunits2-dev \
        libproj-dev \
        libgeos-dev \
        libffi-dev \
        cmake \
        libgtest-dev \
        build-essential \
        curl \
        libcurl4-openssl-dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Ensure compatible setuptools version for cartopy 0.20.3 (requires distutils)
        pip install setuptools==65.5.1
        python -m pip install --upgrade pip==24.0

        # patch to solve dependency issues with celery / fiona / click / pytz
        # download celery package 
        wget https://files.pythonhosted.org/packages/source/c/celery/celery-5.1.2.tar.gz
        tar -xzf celery-5.1.2.tar.gz
        cd celery-5.1.2
        # patch the requirements to use pytz>=2020.1 instead of pytz>dev which causes issues
        sed -i "s/pytz>dev/pytz>=2020.1/g" requirements/default.txt
        sed -i "s/pytz>dev/pytz>=2020.1/g" celery.egg-info/requires.txt
        sed -i "s/pytz>dev/pytz>=2020.1/g" requirements/dev.txt
        # install the package
        python setup.py install
        cd ..
        # remove downlaoded copy of celery
        rm -rf celery-5.1.2 celery-5.1.2.tar.gz

        # Required build tools
        pip install wheel

        # Install shapely and cartopy manually with build isolation OFF
        pip install "numpy<1.24.0"     # to match your constraints
        pip install shapely==1.8.5.post1
        pip install --no-build-isolation cartopy==0.20.3

        pip install pytest-runner
        pip install pyshp
        pip install scipy
        pip install -r stage_requirements.txt
        pip install pytest-cov

      env:
        STAGE: ${{ matrix.stage }}
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
